CC=/usr/local/bin/arm-apple-darwin-gcc -v
CXX=/usr/local/bin/arm-apple-darwin-g++
TARGET=serial
LD=$(CC)
LDFLAGS = -framework CoreFoundation \
          -framework Foundation \
          -framework UIKit \
          -framework LayerKit \
          -framework CoreGraphics \
          -framework GraphicsServices \
          -framework CoreSurface \
          -lobjc

all:	$(TARGET)

Hello:	$(TARGET).o
	$(LD) $(LDFLAGS) -o $@ $^

%.o:	%.m
		$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@

clean:
		rm -f *.o $(TARGET)

